### ISSUE TITLE
Use CpuProfiler::New on Node 10 (as v8's GetCpuProfiler() is deprecated starting Node 10)

### ISSUE THREAD

**Issue by nolanmar511** [GoogleCloudPlatform/cloud-profiler-nodejs#106]
A new API was introduced in v8/v8@120b753.
The current API is deprecated in V8 6.4: v8/v8@8c5e2d7

We use this method [here](https://github.com/GoogleCloudPlatform/cloud-profiler-nodejs/blob/master/bindings/time-profiler.cc#L64), [here](https://github.com/GoogleCloudPlatform/cloud-profiler-nodejs/blob/master/bindings/time-profiler.cc#L70), [here](https://github.com/GoogleCloudPlatform/cloud-profiler-nodejs/blob/master/bindings/time-profiler.cc#L78), and [here](https://github.com/GoogleCloudPlatform/cloud-profiler-nodejs/blob/master/bindings/time-profiler.cc#L83)

Node.js may also have changes in response to this. https://github.com/nodejs/node/issues/18039

**Comment by ofrobots** [comment]
Related #179.
