### ISSUE TITLE
Memory leak in Heap Profiler

### ISSUE THREAD

**Issue by nolanmar511** [GoogleCloudPlatform/cloud-profiler-nodejs#115]
There is a memory leak when using the profiler and collecting just time profiles, just heap profiles, or both time and heap profiles. 
Increasing the rate at which profiles are collected seems to increase the rate at which memory leaks. When using `process.memoryUsage()` to look at memory used, RSS increases notable and heapTotal seems to roughly constant.

**Comment by ofrobots** [comment]
Is the leak in the JavaScript heap or in external heap?

**Comment by nolanmar511** [comment]
External heap.

**Comment by nolanmar511** [comment]
This has been fixed by #117.
