### ISSUE TITLE
Avoid require to load config file

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/cloud-profiler-nodejs#116]
https://github.com/GoogleCloudPlatform/cloud-profiler-nodejs/blob/a7f742d097dfab0cfdf11b0e5844dabb1cc09d65/ts/src/index.ts#L76

If the env. var. points to a .js or .node file, it will be executed. It would be better to read the file as text and then parse as json.

**Comment by aalexand** [comment]
@nolanmar511 Did #161 fix this?

**Comment by ofrobots** [comment]
This should be fixed. @nolanmar511 please double check and close the issue if so.

**Comment by nolanmar511** [comment]
Yes, this is fixed by #161
