### ISSUE TITLE
Node 10: enable e2e tests + memory usage long-running manual test

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/cloud-profiler-nodejs#179]

**Comment by aalexand** [comment]
@nolanmar511 @ofrobots Discussed with Maggie that we should add the e2e testing for ASAP as if any issues show up we get less time every day to merge any fixes. Let's add it today / tomorrow.

@nolanmar511 We should also get a manual long-running test for both CPU and heap profiler to make sure the RSS / heap stats don't have regressions.

**Comment by nolanmar511** [comment]
For long running test with acmeAir and using startLocal (default values for profile collection rate), RSS when using node 10 settled at ~260MiB. With node8, RSS settled at ~240MiB.

So memory consumption is higher with node10, but there don't seem to be any other problems.

**Comment by nolanmar511** [comment]
Also seeming some flakes with the Node10 e2e test (sometimes profile collection rate is slow, and the test seems not to finish)

**Comment by nolanmar511** [comment]
Looking at past runs to get a better idea.

Today's 7am test (node10) had a ~7 minute gap between starting profile creating and getting created profile:
```
...
Tue May 15 14:08:45 UTC 2018: DEBUG:@google-cloud/profiler: Attempting to create profile.
Tue May 15 14:16:13 UTC 2018: DEBUG:@google-cloud/profiler: Successfully created profile WALL.
...
```

Today's 5am  test (node10) had a ~7 minute gap between getting a profile after creation and collecting the profile, and another equally long gap between starting profile creation and getting the created profile:
```
...
Tue May 15 12:08:51 UTC 2018: DEBUG:@google-cloud/profiler: Successfully created profile WALL.
Tue May 15 12:15:11 UTC 2018: DEBUG:@google-cloud/profiler: Successfully collected profile WALL.
...
Tue May 15 12:16:52 UTC 2018: DEBUG:@google-cloud/profiler: Attempting to create profile.
Tue May 15 12:22:45 UTC 2018: DEBUG:@google-cloud/profiler: Successfully created profile WALL.
...
```

The 3am run had a ~11 minute gap between starting profile creation and getting created profile:
```
...
Tue May 15 10:08:46 UTC 2018: DEBUG:@google-cloud/profiler: Attempting to create profile.
Tue May 15 10:19:48 UTC 2018: DEBUG:@google-cloud/profiler: Successfully created profile WALL.
...
```

The 1am run had a ~15 minute gap between starting profile creation and getting created profile:
```
...
Tue May 15 08:08:59 UTC 2018: DEBUG:@google-cloud/profiler: Attempting to create profile.
Tue May 15 08:23:18 UTC 2018: DEBUG:@google-cloud/profiler: Successfully created profile WALL.
...
```
The 11am run had a ~10 minute gap between getting created profile and collecting the profile:
```
...
Tue May 15 06:08:45 UTC 2018: DEBUG:@google-cloud/profiler: Successfully created profile WALL.
Tue May 15 06:19:24 UTC 2018: DEBUG:@google-cloud/profiler: Successfully collected profile WALL.
...
```

I'm inclined to believe that the long pauses occur almost randomly with respect to what the profiler is doing (but show up most frequently between log statements that typically have more time in between them).

Will work on reproducing locally. If that doesn't work, then I'll try reproducing on a GCE instance with minimal resources. Then I want to see if this is more associated with the heap or time profiler.

**Comment by aalexand** [comment]
Also, could you file a separate issue for the problem in hand? This issue is about enabling the e2e test and confirming no regressions in memory overhead, I think that's done. Let's avoid kitchen-sink kind of issues :)

**Comment by nolanmar511** [comment]
Marking this issue as closed. Other node10 issues will be filed separately.

**Comment by nolanmar511** [comment]
Issue with long pauses investigated here: https://github.com/GoogleCloudPlatform/cloud-profiler-nodejs/issues/199
