### ISSUE TITLE
Which profiling configuration settings should the user be able to configure?

### ISSUE THREAD

**Issue by nolanmar511** [GoogleCloudPlatform/cloud-profiler-nodejs#20]
Decide which parameters for profiling (for example, sampling Interval) the use should be able to configure and then make these configurable.

**Comment by aalexand** [comment]
Let's just provide minimal configuration as a start, and then see what customers ask for.

**Comment by ofrobots** [comment]
I would still like to avoid hard coded constants distributed through the code base. If you need to use a constant add it to `internalConfig` object so that we have inventory and a single place to change / promote to regular config.

**Comment by aalexand** [comment]
@ofrobots I filed #24.
