### ISSUE TITLE
GKE Bad Request

### ISSUE THREAD

**Issue by AlexandreAWE** [GoogleCloudPlatform/cloud-profiler-nodejs#202]
Hi,

I try to add Cloud Profiler on my GCP project on Google Cloud Kubernetes Engine.
On Kubernetes pod logs, there is a bad request warning :
```
WARN:: Failed to create profile, waiting 1m 10.3s to try again: Error: Bad Request
```

Here is my startup script : 
```javascript
if (process.env.NODE_ENV === 'production') {
  const serviceContext = {
    service: 'My Service name',
    version: '0.3.0'
  };

  require('@google-cloud/trace-agent').start({
    serviceContext
  });

  require('@google-cloud/profiler').start({ serviceContext });

  require('@google-cloud/debug-agent').start({
    allowExpressions: true,
    serviceContext
  });
}
```
Because I'm on Google Cloud platform, I don't need to use a service account right ?

I don't know if matter but I'm using node:9.10.1-alpine on Docker

Moreover, on API logs, requests about Stackdriver Profiler API have 100% an error status 400 (bad request)

Any idea ?

Thanks

**Comment by aalexand** [comment]
Your service name has wrong pattern, see https://cloud.google.com/profiler/docs/profiling-nodejs#svc-name-and-version.

**Comment by aalexand** [comment]
Basically, do something like 'my-service-name'.

**Comment by ofrobots** [comment]
Is it possible to provide a better error message here? Secondly, I think we should prioritize https://github.com/GoogleCloudPlatform/cloud-profiler-nodejs/issues/81 higher so such configuration isn't even necessary from users.

**Comment by AlexandreAWE** [comment]
as simple as that.. Thanks @aalexand
