### ISSUE TITLE
Add greenkeeper check for package-lock.json

### ISSUE THREAD

**Issue by aalexand** [GoogleCloudPlatform/cloud-profiler-nodejs#210]
From https://github.com/GoogleCloudPlatform/cloud-profiler-nodejs/pull/209#issuecomment-391172365: "This tool can be helpful in keeping the package-lock.json up to date in greenkeeper using repos: https://github.com/greenkeeperio/greenkeeper-lockfile"

**Comment by aalexand** [comment]
@nolanmar511 Closing this as it seems this is no longer necessary as we use Renovate now? Please re-open if it's still relevant.

**Comment by JustinBeckwith** [comment]
We are trying to figure out how to turn on renovate for GoogleCloudPlatform repos (only enabled in googleapis right now).  @theacodes is on the job :)
