### ISSUE TITLE
Drop dependency on extend

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/cloud-profiler-nodejs#23]
The versions of Node this module aims to support have built-in support for [`Object.assign`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) which can be used instead of extend.

**Comment by aalexand** [comment]
Should we just fix it? Or just leave things as is? Not sure how important this is.

**Comment by ofrobots** [comment]
This would be a 'nice-to-have'.

**Comment by nolanmar511** [comment]
I've looked into this, but when I switch to `Object.assign()`, this field is added to the config:   `"interceptors_": [undefined]` (also the type-guarding I have in place stops working, but that is a more minor concern).

**Comment by nolanmar511** [comment]
@ofrobots  -- what would you recommend doing given that `Object.assign()` adds `"interceptors_": [undefined]' to the config?
What does this mean?

**Comment by ofrobots** [comment]
This would have been a nice to have. If fixing this requires effort, it is probably not worth it. Closing.
