### ISSUE TITLE
Import profiler.proto into this project

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/cloud-profiler-nodejs#27]
As far as I can tell, `profile.proto` is a subset of [profiler.proto](https://github.com/googleapis/googleapis/blob/master/google/devtools/cloudprofiler/v2/profiler.proto). Can we drop `profile.proto` and instead vendor in `profiler.proto` instead?

/cc @aalexand

**Comment by aalexand** [comment]
I don't think [profile.proto, aka serialization format for the profiles](https://github.com/google/pprof/blob/master/proto/profile.proto) is a subset of [profiler.proto, aka Stackdriver Profiler API definition](https://github.com/googleapis/googleapis/blob/master/google/devtools/cloudprofiler/v2/profiler.proto), am I missing something?

I thought the discussion in #16 was about avoiding having to have the `RequestProfile` structure which is basically a mirror of what's defined in the API proto.

**Comment by ofrobots** [comment]
I didn't take an exhaustive look, but the js/ts files I generated from `profiler.proto` seems to have quite a few definitions from `profile.proto` already. I'll take a deeper look today.

**Comment by ofrobots** [comment]
Nevermind. This was a result of typos on my part. My `profiler.d.ts` was actually `profile.d.ts`.

**Comment by aalexand** [comment]
@ofrobots Yep, the names are unfortunately impractically similar...
