### ISSUE TITLE
npm test fails if `glcoud` is set up

### ISSUE THREAD

**Issue by fhinkel** [GoogleCloudPlatform/cloud-profiler-nodejs#273]
I use `gcloud` and `npm test` fails because `"projectId": "my-project-id"` shows up in the expected test output.  

```sh
1) createProfiler
       should get have no projectId when no projectId given:

      AssertionError [ERR_ASSERTION]: { logLevel: 2,
  serviceContext: { version: '', service: 'fake-service' },
  disableHeap: true,
  disableTime: true,
  timeIn... deepEqual { projectId: 'tribal-cortex-199921',
  timeIntervalMicros: 1000,
  heapIntervalBytes: 524288,
  heapMaxStackDepth: 64,
  igno...
      + expected - actual

         "localLogPeriodMillis": 10000
         "localProfilingPeriodMillis": 1000
         "localTimeDurationMillis": 1000
         "logLevel": 2
      +  "projectId": "my-project-id"
         "serverBackoffCapMillis": 2147483647
         "serviceContext": {
           "service": "fake-service"
           "version": ""
```

**Comment by nolanmar511** [comment]
I can reproduce -- I have gcloud on my desktop and `npm test` fails in this way if I set the GCLOUD_PROJECT enviroment variable.

The `util.normalizeArguments()` function (from `@google-cloud/common`) initializes the projectId with this value. 

We already clear `process.env`. So I think the best solution is to restructure the code and tests.

**Comment by nolanmar511** [comment]
I made an error -- we do clear `process.env`, but not before initializing the `defaultConfig`.

**Comment by nolanmar511** [comment]
#275 should fix this.
