### ISSUE TITLE
Google Cloud Profiler fails to to install using either Yarn or Npm

### ISSUE THREAD

**Issue by xkLander** [GoogleCloudPlatform/cloud-profiler-nodejs#287]
When I run "yarn install" i get a ton of node gyp errors, and also the failure to install the @google-cloud/profiler , I have tried this multiple times, I am using docker, and also running ./build.sh throws the same error. 
4/4] Rebuilding all packages...
[1/11] ⠠ grpc
[6/11] ⠠ @google-cloud/profiler
[3/11] ⠠ grpc
[7/11] ⠠ speaker
error G:\myProject\node_modules\@google-cloud\profiler: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: G:\SmyProject\node_modules\@google-cloud\profiler

**Comment by soldair** [comment]
would you mind providing your npm-debug.log? you can link it from a gist. =)

**Comment by nolanmar511** [comment]
The npm-debug logs would still be appreciated.
The profiler has a native component and we don't (yet) have pre-compiled binaries. Given that installation failed during node-gyp rebuild, the problem seems to be with compilation.

**Comment by xkLander** [comment]
The issue was with Docker having a small image of Alpine Node which does not include Python v2.7 which works for node gyp, and other dependencies. To fix this, i referred to this issue in docker-node [282](https://github.com/nodejs/docker-node/issues/282)

The issue was not related to google profiler, rather it had to do with docker-node image.
