### ISSUE TITLE
Kokoro builds are failing some new presubmit checks

### ISSUE THREAD

**Issue by aalexand** [GoogleCloudPlatform/cloud-profiler-nodejs#300]
E.g. for #259, see below. @nolanmar511 please talk to @JustinBeckwith on how to fix these.

<img width="802" alt="screen shot 2018-09-25 at 11 48 40 am" src="https://user-images.githubusercontent.com/1519040/46035895-06c72f80-c0b9-11e8-921f-8732c9eebf4a.png">

**Comment by nolanmar511** [comment]
Also cc/ @kinwa91.

I'm guessing these tests may have started running prematurely because we have a webhook setup for our e2e kokoro test.

**Comment by aalexand** [comment]
@kinwa91 Did you have a chance to look at it? I am removing @nolanmar511 from assignees for now.

**Comment by nolanmar511** [comment]
I had a CL to disable these. I'll try to get it in.

**Comment by nolanmar511** [comment]
We've removed the internal Kokoro configs that caused these tests to be run before they were ready to be run. 

Closing this, since these tests are no longer running.
