### ISSUE TITLE
Wall time shows 100% idle

### ISSUE THREAD

**Issue by koistya** [GoogleCloudPlatform/cloud-profiler-nodejs#302]
![image](https://user-images.githubusercontent.com/197134/46150069-63227e80-c274-11e8-9eb5-b7e170ae66f2.png)

**Comment by aalexand** [comment]
@nolanmar511 PTAL

**Comment by nolanmar511** [comment]
It's not necessarily unexpected for a Wall Time profile to show 100% of time spent in "(idle)". 
For example, when profiling a server that is not under load (or under a very light load), it's very likely that the the server isn't doing anything.

@koistya -- Could you provide more details about what you were profiling?

**Comment by nolanmar511** [comment]
For now, I'm closing this issue, since wall time profiles can be 100% idle when the profiler is working as intended.

Feel free to re-open if you think that the wall profiler is not working as intended.
