### ISSUE TITLE
installing with npm

### ISSUE THREAD

**Issue by nolanmar511** [GoogleCloudPlatform/cloud-profiler-nodejs#45]
Right now, when I try `npm install https://github.com/GoogleCloudPlatform/cloud-profiler-nodejs.git`, I get 

```
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git submodule update -q --init --recursive
npm ERR! fatal: No url found for submodule path 'third_party/googleapis/third_party/boringssl-with-bazel' in .gitmodules
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /usr/local/google/home/nolanmar/.npm/_logs/2017-11-02T22_08_07_487Z-debug.log
```

Previously, when I tried to install from github, the typescript wasn't compiled to javascript.

@ofrobots -- any tips on how to make this work? I'm also open to just making an npm module, if that's easier.  We'd like for there to be a way for users to install this module pretty soon so we can start testing that out a bit more.

**Comment by ofrobots** [comment]
Fix in #46.

If we want users to be able to install the module, then we should publish a module for this pretty soon anyway.
