### ISSUE TITLE
Time profiler memory leak on Node.js 8

### ISSUE THREAD

**Issue by aalexand** [GoogleCloudPlatform/cloud-profiler-nodejs#92]
Filing to mirror https://github.com/nodejs/node/issues/14894. See also https://bugs.chromium.org/p/v8/issues/detail?id=6623.

Per that issue, the fix is already available in Node.js 9.3.0. This issue will be closed when there is a Node.js 8 version with the fix available.

**Comment by ofrobots** [comment]
The 8.x backport has landed on https://github.com/nodejs/node/pull/17659. This should be in the release candidate build today.

**Comment by nolanmar511** [comment]
I've confirmed that the memory leak has been fixed in node 8.9.4. 
This has been fixed.
